### ISSUE TITLE
Questions regarding scala.ScalaReflectionException

### ISSUE THREAD

**Issue by RuizhuYang** [Kotlin/kotlin-spark-api#194]
We're building spark application on AWS EMR service, and seeing error when running the application:
```
Exception in thread "main" scala.ScalaReflectionException: object org.apache.spark.sql.KotlinReflection not found.
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:185)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:29)
	at org.apache.spark.sql.KotlinReflection$$typecreator1$6.apply(KotlinReflection.scala:777)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe$lzycompute(TypeTags.scala:237)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe(TypeTags.scala:237)
	at org.apache.spark.sql.KotlinReflection.localTypeOf(KotlinReflection.scala:1404)
	at org.apache.spark.sql.KotlinReflection.localTypeOf$(KotlinReflection.scala:1402)
	at org.apache.spark.sql.KotlinReflection$.localTypeOf(KotlinReflection.scala:53)
	at org.apache.spark.sql.KotlinReflection$.$anonfun$serializerFor$1(KotlinReflection.scala:777)
	at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:73)
	at org.apache.spark.sql.KotlinReflection.cleanUpReflectionObjects(KotlinReflection.scala:1389)
	at org.apache.spark.sql.KotlinReflection.cleanUpReflectionObjects$(KotlinReflection.scala:1388)
	at org.apache.spark.sql.KotlinReflection$.cleanUpReflectionObjects(KotlinReflection.scala:53)
	at org.apache.spark.sql.KotlinReflection$.serializerFor(KotlinReflection.scala:694)
	at org.apache.spark.sql.KotlinReflection$.serializerFor(KotlinReflection.scala:681)
	at org.apache.spark.sql.KotlinReflection.serializerFor(KotlinReflection.scala)
	at org.jetbrains.kotlinx.spark.api.EncodingKt.kotlinClassEncoder(Encoding.kt:165)
	at org.jetbrains.kotlinx.spark.api.EncodingKt.generateEncoder(Encoding.kt:144)
```
I can confirm that that runtime uses Spark 3.3.0, Scala 2.12, and we use the matching version of koltin-spark-api `org.jetbrains.kotlinx.spark:kotlin-spark-api_3.3.0_2.12:1.2.1` and `org.jetbrains.kotlinx.spark:core-3.3.0_2.12:1.2.1` 

This seems like an issue of missing dependency. Any thoughts on which dependency we should check?

Thanks!

**Comment by Jolanrensen** [comment]
Hi! I don't think an explicit dependency on the "core" module is needed as "kotlin-spark-api" already provides it as an "api" dependency. Could you try it without? Also, currently, we're at version 1.2.3. Just to be safe, could you upgrade?

**Comment by RuizhuYang** [comment]
Hi @Jolanrensen, 

Thanks for you quick response!

I have tried to update `org.jetbrains.kotlinx.spark:kotlin-spark-api_3.3.0_2.12:1.2.1` to `org.jetbrains.kotlinx.spark:kotlin-spark-api_3.3.0_2.12:1.2.3`, and exclude the dependency of `org.jetbrains.kotlinx.spark:core-3.3.0_2.12` in my project. But this time we get another error 

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jetbrains/kotlinx/spark/extensions/KSparkExtensions
	at org.jetbrains.kotlinx.spark.api.SparkSessionKt.getSparkContext(SparkSession.kt:230)
	at com.amazon.galaxy.infar.buying.pipeline.BuyingPipelineEngine.run(BuyingPipelineEngine.kt:119)
	at com.amazon.galaxy.infar.buying.local.DriverTestWithLocalFilesKt.main(DriverTestWithLocalFiles.kt:51)
	at com.amazon.galaxy.infar.buying.local.DriverTestWithLocalFilesKt.main(DriverTestWithLocalFiles.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1006)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1095)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1104)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlinx.spark.extensions.KSparkExtensions
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 16 more
```

Can we know where this class is defined? I cannot find it in any of the dependency package. Thanks!

**Comment by Jolanrensen** [comment]
The specific class that is missing for you is in the [core module](https://github.com/Kotlin/kotlin-spark-api/blob/release/core/src/main/scala/org/apache/spark/sql/KotlinReflection.scala). But it should be included in your build nonetheless, so I think it's something specific to Amazon's version of Spark that's causing the issue. Do you have an overview of your other dependencies exactly? Or is that hidden by AWS? Otherwise I could try and reproduce it.

A (module) dependency can, among others, consist of "implementation" and "api". Implementation will include the dependency only to this package. Api will do that too but also expose all the methods of the dependency to users of this package, essentially forwarding them. This means that you should have access to the KotlinReflection class from the core module if you just have kotlin-spark-api as a dependency. https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by RuizhuYang** [comment]
Hi @Jolanrensen,

After talking with AWS EMR team, we found out that it is an issue for their latest release EMR 6.9.0 version. There are some issues for class loader compatibility. After we down grade to EMR 6.8.0 version, this got resolved. 

Thanks so much for your help!

**Comment by IdaliaCampoverdeQxq** [comment]
Hi @RuizhuYang,

Based on the error message, it seems like the org.apache.spark.sql.KotlinReflection class cannot be found at runtime. This could indeed be caused by a missing dependency.

You mentioned that you are using the matching version of kotlin-spark-api and core for Spark 3.3.0 and Scala 2.12, which is good. However, it's possible that there may be other dependencies that are missing or incompatible.

One thing you could try is checking the transitive dependencies of the kotlin-spark-api and core libraries using a tool like sbt-dependency-graph. This will give you a tree of all the dependencies, which may help you identify any missing or incompatible libraries.

Another thing to check is whether the necessary Spark jars are included in the classpath at runtime. You could try printing out the classpath to see if the necessary Spark jars are included.

**Comment by jhardin** [comment]
@RuizhuYang We're facing similar `ScalaReflectionException` issues in later versions of EMR (but with our own case classes) when running JREs other than `1.8` (our application works fine with `1.8` JRE).  Do you know if your issue has been resolved in versions of EMR > `emr-6.8.0`?
